services:
  - type: web
    name: nersocials-api
    runtime: python
    repo: https://github.com/nereadnan1-bit/NerSocials
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true

  - type: static
    name: nersocials-frontend
    repo: https://github.com/nereadnan1-bit/NerSocials
    branch: main
    rootDir: frontend
    publishDir: .
    envVars:
      - key: BACKEND_URL
        value: https://nersocials-api.onrender.com